apiVersion: v1
kind: Namespace
metadata:
  name: rustcost
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rustcost
  namespace: rustcost
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rustcost
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
      - deployments
      - nodes
      - pods
      - services
      - resourcequotas
      - replicationcontrollers
      - limitranges
      - persistentvolumeclaims
      - persistentvolumes
      - namespaces
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
      - deployments
      - daemonsets
      - replicasets
    verbs:
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - batch
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rustcost
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rustcost
subjects:
  - kind: ServiceAccount
    name: rustcost
    namespace: rustcost
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustcost
  namespace: rustcost
  labels:
    app: rustcost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rustcost
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rustcost
    spec:
      serviceAccountName: rustcost
      containers:
        - name: rustcost
          image: kimc1992/rustcost:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: rustcost-secret
                  key: DATABASE_URL
            - name: PORT
              value: "3000"
            - name: HOST
              value: "0.0.0.0"
            - name: RUST_LOG
              value: "info"
            # TOKEN_PATH, CA_PATH, API_SERVER use Kubernetes service account defaults
          resources:
            requests:
              cpu: "10m"
              memory: "55Mi"
            limits:
              cpu: "999m"
              memory: "1Gi"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 1001
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir: {}